language: ruby
bundler_args: --without debug extra
sudo: false
cache: bundler
before_install:
  - gem install bundler
script: bundle exec rake test_with_coveralls
rvm:
  - 2.2
  - 2.1
  - 2.0
  - jruby-19mode
  - rbx-2
notifications:
  email:
    - sk@semicolon.at
    - namyra@gmail.com
  on_success: change
  on_failure: always
