language: ruby
bundler_args: --without debug extra
sudo: false
cache: bundler
before_install:
  - gem install bundler
script: bundle exec rake test_with_coveralls
rvm:
  - 2.3
  - 2.2.5
  - jruby-9.0.5.0
  - rbx-2.2.7
notifications:
  email:
    - sk@semicolon.at
    - namyra@gmail.com
  on_success: change
  on_failure: always
matrix:
  allow_failures:
   - rvm: rbx-2.2.7
