language: ruby
bundler_args: --without debug extra
sudo: false
cache: bundler
before_install:
  - gem install bundler
script: bundle exec rake test_with_coveralls
rvm:
  - 2.5.0
  - 2.4.3
  - 2.3.6
  - 2.2.9
  - jruby-9.1.16.0
notifications:
  email:
    - sk@semicolon.at
    - namyra@gmail.com
  on_success: change
  on_failure: change
