name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    environment: CI
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby-version:
          - 2.7
          - 3.0
          - 3.1
          - jruby

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: actions/setup-ruby@v2
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Run tests
        run: bundle exec rake

      - name: Upload coverage results
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
